name: baseball_tapped_out
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/

  fonts:
    - family: Pixelify Sans
      fonts:
        - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
